### ISSUE TITLE
Can't find Helper md-5

### ISSUE THREAD

**Issue by hank-harvey** [maads/ember-cli-md5#1]
When I follow the README and attempt to use the add on I receive this error in the console 
`Error: Assertion Failed: A helper named 'md-5' could not be found` 
Any and all help is appreciated. 
Thanks.

**Comment by maads** [comment]
This error might be shown if you are using `{{md-5 }}` without it being properly installed.

Try running the installation commands again:
`npm install --save-dev ember-cli-md5`
`ember generate md-5`

**Comment by stevetyler** [comment]
ember generate helper md-5 works for me.
